xsd2php:
  namespaces:
    'http://www.w3.org': 'InterInvest\AsponeBundle\Entity\Tva'
  destinations_php:
    'InterInvest\AsponeBundle\Entity\Tva': InterInvest/AsponeBundle/Entity/Tva
  destinations_jms:
    'InterInvest\AsponeBundle\Entity\Tva': InterInvest/AsponeBundle/Entity/Tva
  naming_strategy: long # optional and default